from app import db, user_collection, equipment_collcetion, organic_carbon_nitrogent_collection, ph_trace_form_collection, soil_analysis_form_collection, trace_worksheet_collection, water_worksheet_collection, water_analysis_collection
from datetime import datetime, timedelta
import random